set nocompatible
set nobackup
" disable ex mode
nnoremap Q <Nop>

filetype on
filetype plugin on
filetype indent on

set history=1000
set nobackup

" display file matches after tab completion
set wildmenu
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
" recursive file search
set path+=**

" visuals
let &t_SI = "\e[5 q"
let &t_EI = "\e[2 q"
let &t_SR.= "\e[4 q"

colorscheme wildcharm

syntax on

set showcmd
set showmode

set report=0

" status line
set statusline=
set statusline+=\ %f\ %Y\ %R
" separate the left and right side.
set statusline+=%=
set statusline+=\ %M\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\/%L\ col:\ %c\ percent:\ %p%%
set laststatus=2

" navigate the split view CTRL+j, CTRL+k, CTRL+h, or CTRL+l
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
" resize split windows using arrow keys by pressing CTRL+UP, CTRL+DOWN, CTRL+LEFT, or CTRL+RIGHT
noremap <C-up> <C-w>+
noremap <C-down> <C-w>-
noremap <C-left> <C-w>>
noremap <C-right> <C-w><

" line config
set nowrap
set cursorline
set number relativenumber

" indentation
set shiftwidth=4
set tabstop=4
set expandtab

" no double spaces after joining lines
set nojoinspaces

" search
set incsearch
set showmatch
set hlsearch

" keymap
let mapleader = ","
nnoremap <space> :!

" purge
vnoremap <leader>d "_d
" copy to clipboard
vnoremap <leader>y "+y

" select all
nnoremap <C-a> ggVG
" insert new line
nnoremap <leader>n o<ESC>k

" java test (public) method
nnoremap ,jtest i@Test<ESC>>>ovoid X() {<ESC>>>o// given<ESC>>>>>o<CR>// when<ESC>>>>>o<CR>// then<ESC>>>>>o<CR>}<ESC>>>7k_fXciw
nnoremap ,jptest i@Test<ESC>>>opublic void X() {<ESC>>>o// given<ESC>>>>>o<CR>// when<ESC>>>>>o<CR>// then<ESC>>>>>o<CR>}<ESC>>>7k_fXciw

